# Generated by Django 2.2.5 on 2019-12-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjongapp', '0002_usermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='goodRule',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='remarks',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='specialty',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
