# Generated by Django 2.2.5 on 2019-12-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjongapp', '0004_eventdetailmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
