# Generated by Django 2.2.5 on 2020-01-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahjongapp', '0005_eventmodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdetailmodel',
            options={'verbose_name': 'イベント詳細モデル'},
        ),
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'verbose_name': 'イベントモデル'},
        ),
        migrations.AlterModelOptions(
            name='eventparticipantmodel',
            options={'verbose_name': 'イベント合計モデル'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'ユーザモデル'},
        ),
        migrations.AlterField(
            model_name='eventparticipantmodel',
            name='eventId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='EventModel', to='mahjongapp.EventModel', verbose_name='title'),
        ),
    ]
