# Generated by Django 2.2.5 on 2020-01-01 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahjongapp', '0006_auto_20200101_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetailmodel',
            name='eventId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='eventDetailModel_eventId', to='mahjongapp.EventModel', verbose_name='eventDetailModel_eventId'),
        ),
        migrations.AlterField(
            model_name='eventparticipantmodel',
            name='eventId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='eventParticipantModel_eventId', to='mahjongapp.EventModel', verbose_name='eventParticipantModel_eventId'),
        ),
    ]
