# Generated by Django 2.2.5 on 2020-01-01 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahjongapp', '0007_auto_20200101_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetailmodel',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='eventDetailModel_userId', to='mahjongapp.UserModel', verbose_name='eventDetailModel_userId'),
        ),
        migrations.AlterField(
            model_name='eventparticipantmodel',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='eventParticipantModel_userId', to='mahjongapp.UserModel', verbose_name='eventParticipantModel_userId'),
        ),
    ]
