# Generated by Django 2.2.5 on 2020-01-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjongapp', '0008_auto_20200101_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='roundCnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
