# Generated by Django 2.2.5 on 2020-01-03 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahjongapp', '0009_auto_20200103_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='winnerId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='event_winnerId', to='mahjongapp.UserModel', verbose_name='event_winnerId'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='author',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='goodRule',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
