# Generated by Django 2.2.5 on 2020-01-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahjongapp', '0010_auto_20200103_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipantmodel',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventparticipantmodel',
            name='remarks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='eventparticipantmodel',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EventRoundModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundId', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('remarks', models.TextField(default='')),
                ('eventId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='EventRoundModel_eventId', to='mahjongapp.EventModel', verbose_name='EventRoundModel_eventId')),
            ],
            options={
                'verbose_name': 'イベントラウンド合計モデル',
            },
        ),
    ]
