# Generated by Django 2.2.5 on 2020-01-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjongapp', '0011_auto_20200103_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventroundmodel',
            name='remarks',
            field=models.TextField(default='', null=True),
        ),
    ]
