# Generated by Django 2.2.5 on 2020-01-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjongapp', '0012_auto_20200103_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventroundmodel',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
