# Generated by Django 2.2.5 on 2020-01-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahjongapp', '0013_auto_20200103_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdetailmodel',
            options={'verbose_name_plural': 'イベント詳細モデル'},
        ),
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'verbose_name_plural': 'イベントモデル'},
        ),
        migrations.AlterModelOptions(
            name='eventparticipantmodel',
            options={'verbose_name_plural': 'イベント合計モデル'},
        ),
        migrations.AlterModelOptions(
            name='eventroundmodel',
            options={'verbose_name_plural': 'イベントラウンド合計モデル'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name_plural': 'ユーザモデル'},
        ),
    ]
