# Generated by Django 2.2.5 on 2020-01-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjongapp', '0015_auto_20200103_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
    ]
